# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Sample an entire vector of healthstates
#'
#' This function takes a vector of probabilities and an integer value `m`, and optionally a seed,
#' and returns a sampled vector based on the provided probabilities.
#'
#' @param probs A numeric vector of probabilities.
#' @param m An integer indicating the number of samples to return.
#' @param seed An optional integer that sets the random seed for reproducibility.
#' @return A numeric vector of sampled values.
#' @examples
#' samplev_cpp(c(0.1, 0.9), 5)
#' @export
samplev_cpp <- function(probs, m, seed = 1L) {
    .Call(`_samplev_samplev_cpp`, probs, m, seed)
}

